name: fed-env  # name of the environment

channels:
  - defaults
  - conda-forge
  
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pip
  - pip:
    - requests